# Generated by Django 3.1.2 on 2021-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210331_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('name',), 'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
